swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Specify possible API endpoints for Argent Bank development phase 2 (concerning transactions)
  version: 1.0.0
  termsOfService: 'http://swagger.io/terms'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/profile/{accountId}:
    get:
      tags:
        - User Transactions
      summary: User's accounts
      description: API to get all accounts
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attached Bearer JWT token
          required: true
        - name: accountId
          in: path
          description: user's Account Id
          required: true
          type: string
      responses:
        '200':
          description: Transactions successfully retrieved
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/profile/{accountId}/transactions:
    get:
      tags:
        - User Transactions
      summary: User Transactions for current month
      description: API to get all transactions for current month
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attached Bearer JWT token
          required: true
        - in: path
          type: string
          name: accountId
          description: User's account Id
          required: true
      responses:
        '200':
          description: Transactions successfully retrieved
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/accounts/{accountId}/transactions/{transactionId}:
    get:
      tags:
        - User Transactions
      summary: Transaction details
      description: API for getting single transaction details
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attached Bearer JWT token
          required: true
        - in: path
          type: string
          name: accountId
          description: User's account Id
          required: true
        - in: path
          type: string
          name: transactionId
          description: Transaction's Id
          required: true
      responses:
        '200':
          description: Transaction successfully retrieved
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      tags:
        - User Transactions
      summary: Update transaction
      description: Update transaction's details
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attached Bearer JWT token
          required: true
        - in: path
          type: string
          name: accountId
          description: User's account Id
          required: true
        - in: path
          type: string
          name: transactionId
          description: Transaction's Id
          required: true
        - in: body
          name: body
          description: Update transaction attributes
          required: true
          schema:
            $ref: '#/definitions/TransactionDetail'
      responses:
        '200':
          description: Transaction successfully retrieved
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  Transactions:
    type: object
    properties:
      transactionId:
        type: string
      date:
        type: string
      description:
        type: string
      amount:
        type: number
      category:
        type: string
  TransactionDetail:
    type: object
    properties:
      description:
        type: string
      category:
        type: string


